# Generated by Django 3.2.5 on 2022-07-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220714_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='breaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='times_read',
            field=models.IntegerField(default=0),
        ),
    ]
